### ISSUE TITLE
pyalarmdotcomajax not installed properly

### ISSUE THREAD

**Issue by akinomeroglu** [uvjustin/alarmdotcomajax#1]
Hello,

I try to setup this custom comp. in Hass.io. As far as I understand dependency not installed. I try to restart couple of time.

This is my error log

```
Platform error: alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 752, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 277, in get_platform
    f"{self.pkg_path}.{platform_name}"
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/alarmdotcomajax/alarm_control_panel.py", line 5, in <module>
    from pyalarmdotcomajax import Alarmdotcom
ModuleNotFoundError: No module named 'pyalarmdotcomajax'
```

This is my config

#home_alarm
alarm_control_panel:
  platform: alarmdotcomajax
  username: !secret alarm_username
  password: !secret alarm_password

Thanks

**Comment by uvjustin** [comment]
Did you install the pyalarmdotcomajax library using pip?

**Comment by akinomeroglu** [comment]
@uvjustin I am using hass.io so I don't have any access to it's shell. Homeassistant must be install this dependecy while booting.

**Comment by uvjustin** [comment]
I don't use hass.io but I think hass.io is supposed to install the dependency automatically. Is the manifest.json in the directory?

**Comment by akinomeroglu** [comment]
@uvjustin I think I understand the root cause. Your manifest.json file is not valid because of "codeowners": [@uvjustin] line. It must be "codeowners": ["@uvjustin"] IMHO. This correction fixed my problem

**Comment by uvjustin** [comment]
Thanks for catching that. I will fix that
