### ISSUE TITLE
Error setting up integration alarm_control_panel - received exception

### ISSUE THREAD

**Issue by Raul-7-7** [uvjustin/alarmdotcomajax#18]
Hi,
I followed the instruction and getting an error. Here is my setup
/config/custom_components/alarmdotcomajax 
---> __init__.py
---> alarm_control_panel.py
---> manifest.json

I then added the following to my config.yaml 
alarm_control_panel:
  - platform: alarmdotcomajax
    username: XXXXXXXX
    password: XXXXXXX
    code: "XXXXX"
    force_bypass: "true"
    no_entry_delay: "home"
    silent_arming: "false"

When I reboot the HA, I get this error: 
`Logger: homeassistant.bootstrap
Source: loader.py:516
First occurred: 13:14:08 (1 occurrences)
Last logged: 13:14:08

Error setting up integration alarm_control_panel - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 64, in async_setup_component
    return await task  # type: ignore
  File "/usr/src/homeassistant/homeassistant/setup.py", line 174, in _async_setup_component
    processed_config = await conf_util.async_process_component_config(
  File "/usr/src/homeassistant/homeassistant/config.py", line 809, in async_process_component_config
    p_integration = await async_get_integration_with_requirements(hass, p_name)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 48, in async_get_integration_with_requirements
    integration = await async_get_integration(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 456, in async_get_integration
    integration = Integration.resolve_legacy(hass, domain)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 241, in resolve_legacy
    comp = _load_file(hass, domain, _lookup_path(hass))
  File "/usr/src/homeassistant/homeassistant/loader.py", line 516, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/alarmdotcomajax/__init__.py", line 6
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax`

**Comment by Raul-7-7** [comment]
I also installed the depencies manually, by running **pip install beautifulsoup4 pyalarmdotcomajax==0.1.3**

**Comment by Raul-7-7** [comment]
NVM got it working!!! for some reason you need to download the zip and unzip on the host, if you download each file 1 at a time, doesnt work! thank you!!!
